sudo: required

services:
    - docker

jobs:
    include:
        - stage: Backend Unit Tests
          script:
              - docker-compose run backend python3 -m unittest discover
        - stage: Frontend Unit Tests
          script:
              - docker-compose run frontend npm test

notifications:
    email: false
